#starship.toml

scan_timeout = 300
add_newline = false
format = "$time${env_var.VIRTUAL_ENV_PROMPT}$username$hostname$battery[:](white)$directory$git_branch$git_status ${custom.root_char}${custom.user_char}$character"

[time]
utc_time_offset="1"
disabled = false
time_format = "%H%M"
format = "[$time]($style)[:](white)"
style = "#3755ff bold"

[custom.root_char]
command = 'echo "$"'
format  = "[$output](bold green)"
when    = '[ $(sudo -n true 2>/dev/null; echo $?) -ne 0 ]'

[custom.user_char]
command = 'echo "#"'
format  = "[$output](bold bright-yellow)"
when    = '[ $(sudo -n true 2>/dev/null; echo $?) -eq 0 ]'

[character]
success_symbol = "[> ](bold green)"
error_symbol   = "[> ](bold red)"
vicmd_symbol   = "[< ](bold bright-yellow)"
format = "$symbol(bold)"

[env_var.VIRTUAL_ENV_PROMPT]
format = '($env_value)'

[directory]
style = "bold #707eff"
format = "[$path]($style)"
truncation_length = 3

[git_branch]
symbol = ""
format = "[@$branch]($style)"
style = "bold purple"

[git_status]
conflicted = "[X](red bold)"
staged     = "[S](green bold)"
modified   = "[+](green bold)"
renamed    = "[~](white bold)"
deleted    = "[-](red bold)"
untracked  = "[?](white bold)"
stashed    = "[∆](white)"
ahead      = "[↑${count}](yellow bold)"
behind     = "[↓${count}](red bold)"
diverged   = "[¦${ahead_count}/${behind_count}](red)"
up_to_date = ""

disabled = false
ignore_submodules = true

format = '[\[](bold purple)[$all_status$ahead_behind]($style)[\]](bold purple)'

[package]
format = "[$symbol$version]($style)"

[python]
format = '[$version]($style)'
detect_extensions = []
detect_files      = []
detect_folders    = []

[username]
show_always = true
format = "[$user](cyan bold)[@](green bold)"

[hostname]
ssh_only = false
format = "[$hostname](green bold)"

[battery]
disabled = false
format = '[\[](green bold)[$percentage]($style)[\]](green bold)'

#PYTHONANCHOR_REPLACE
