#starship.toml

scan_timeout = 300
add_newline = false
format = "$time${env_var.VIRTUAL_ENV_PROMPT}$username$hostname$battery[:](white)$directory$git_branch$git_status ${custom.sudo_char}$character"

[time]
utc_time_offset="1"
disabled = false
time_format = "%H%M"
format = "[$time]($style)[:](white)"
style = "bold #707eff"

[custom.sudo_char]
command = 'if [ "$(cat "$SUDO_CACHE_FILE" 2>/dev/null)" = "1" ]; then echo -e "\x1b[38;2;255;255;0m#"; else echo -e "\x1b[38;2;0;255;0m$"; fi;'
format  = "[$output](white)"
when    = 'true'

[character]
success_symbol = "[> ](bold bright-green)"
error_symbol   = "[> ](bold red)"
vicmd_symbol   = "[< ](bold bright-yellow)"
format = "$symbol(bold)"

[env_var.VIRTUAL_ENV_PROMPT]
format = '($env_value)'

[directory]
style = "bold #707eff"
format = "[$path]($style)"
truncation_length = 3

[git_branch]
symbol = ""
format = "[@$branch]($style)"
style = "bold bright-purple"

[git_status]
conflicted = "[X](red bold)"
staged     = "[S](bright-green bold)"
modified   = "[+](bright-green bold)"
renamed    = "[~](white bold)"
deleted    = "[-](red bold)"
untracked  = "[?](white bold)"
stashed    = "[∆](white)"
ahead      = "[↑${count}](bright-yellow bold)"
behind     = "[↓${count}](red bold)"
diverged   = "[¦${ahead_count}/${behind_count}](red)"
up_to_date = ""

disabled = false
ignore_submodules = true

format = '[\[](bold bright-purple)[$all_status$ahead_behind]($style)[\]](bold bright-purple)'

[package]
format = "[$symbol$version]($style)"

[python]
format = '[$version]($style)'
detect_extensions = []
detect_files      = []
detect_folders    = []

[username]
show_always = true
format = "[$user](bright-cyan bold)[@](bright-green bold)"

[hostname]
ssh_only = false
format = "[$hostname](bright-green bold)"

[battery]
disabled = false
format = '[\[](bright-green bold)[$percentage]($style)[\]](bright-green bold)'

#PYTHONANCHOR_REPLACE
